In [1]:
import pandas as pd

df = pd.read_csv("../data/telco_cleaned.csv")

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [2]:
df["charge_category"] = pd.cut(
    df["MonthlyCharges"],
    bins=[0, 40, 70, 120],
    labels=["Low", "Medium", "High"]
)

df[["MonthlyCharges", "charge_category"]].head()

   MonthlyCharges charge_category
0           29.85             Low
1           56.95          Medium
2           53.85          Medium
3           42.30          Medium
4           70.70            High

In [3]:
df["tenure_group"] = pd.cut(
    df["tenure"],
    bins=[0, 12, 24, 48, 72],
    labels=[
        "0-1 year",
        "1-2 years",
        "2-4 years",
        "4-6 years"
    ]
)

df[["tenure", "tenure_group"]].head()

   tenure tenure_group
0       1     0-1 year
1      34    2-4 years
2       2     0-1 year
3      45    2-4 years
4       2     0-1 year

In [4]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn',
       'charge_category', 'tenure_group'],
      dtype='object')

In [5]:
df["charge_category"].value_counts()

charge_category
High      3583
Low       1838
Medium    1622
Name: count, dtype: int64

In [6]:
df["tenure_group"].value_counts()

tenure_group
4-6 years    2239
0-1 year     2175
2-4 years    1594
1-2 years    1024
Name: count, dtype: int64

In [7]:
df.to_csv("../data/telco_featured.csv", index=False)

print("Featured dataset saved successfully")

Featured dataset saved successfully