In [1]:
import pandas as pd

df = pd.read_csv("../data/telco_featured.csv")

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,charge_category,tenure_group
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,Low,0-1 year
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,One year,No,Mailed check,56.95,1889.50,No,Medium,2-4 years
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,Medium,0-1 year
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,Medium,2-4 years
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,High,0-1 year

In [2]:
total_customers = len(df)

print("Total Customers:", total_customers)

Total Customers: 7043

In [3]:
churned_customers = len(df[df["Churn"] == "Yes"])

print("Churned Customers:", churned_customers)

Churned Customers: 1869

In [4]:
churn_rate = (
    churned_customers / total_customers
) * 100

print("Churn Rate: {:.2f}%".format(churn_rate))

Churn Rate: 26.54%

In [5]:
churned = df[df["Churn"] == "Yes"]

revenue_loss = churned["MonthlyCharges"].sum()

print("Revenue Loss:", revenue_loss)

Revenue Loss: 139130.85

In [6]:
contract_churn = pd.crosstab(
    df["Contract"],
    df["Churn"]
)

contract_churn

Churn             No   Yes
Contract
Month-to-month  2220  1655
One year        1307   166
Two year        1647    48

In [7]:
pd.crosstab(
    df["tenure_group"],
    df["Churn"]
)

Churn           No   Yes
tenure_group
0-1 year      1138  1037
1-2 years      730   294
2-4 years     1269   325
4-6 years     2026   213

1. Focus on retaining month-to-month customers.

2. Encourage customers to switch to long-term contracts.

3. Provide discounts for new customers during first year.

4. Target high-value customers before they churn.

5. Improve customer support and engagement.

In [9]:
import os

print("DATA FILES:")
print(os.listdir("../data"))

print("\nREPORT FILES:")
print(os.listdir("../reports"))

print("\nSRC FILES:")
print(os.listdir("../src"))

DATA FILES:
['.ipynb_checkpoints', 'telco_cleaned.csv', 'telco_featured.csv', 'telco_raw.csv']

REPORT FILES:
['churn_distribution.png', 'contract_vs_churn.png', 'correlation_heatmap.png', 'tenure_vs_churn.png']

SRC FILES:
['.ipynb_checkpoints', 'business_impact.py', 'data_cleaner.py', 'data_loader.py', 'eda_plots.py', 'feature_engineer.py', '__init__.py']